version: '3.8'

services:


  webapi:
    build:
      context: .
      dockerfile: Intcomex.ProductsApi.API/Dockerfile
    container_name: webapi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=IntcomexDb;User Id=sa;Password=1n7Com3x02062025;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - appnetwork

networks:
  appnetwork:
