name: Build and Deploy API

on:
  push:
    branches:
      - main  # Puedes cambiar a 'master' si es tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Docker
      uses: docker/setup-buildx-action@v2

    - name: Login a Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir imagen Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/products-api:latest .

    - name: Publicar imagen en Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/products-api:latest
