name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Intcomex.ProductsApi.API.sln

      - name: Build solution
        run: dotnet build Intcomex.ProductsApi.API.sln --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test Intcomex.ProductsApi.Tests/Intcomex.ProductsApi.Tests.csproj --configuration Release --no-build --verbosity normal
